# Generated by Django 5.2.17 on 2026-08-04 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('registration_closed', 'RegistrationClosed'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=32)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('registration_starts_at', models.DateTimeField(blank=True, null=True)),
                ('registration_ends_at', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='Asia/Jerusalem', max_length=64)),
                ('default_language', models.CharField(default='ru', max_length=8)),
                ('supported_languages', models.JSONField(default=list)),
                ('max_guests', models.PositiveIntegerField(default=10)),
                ('allow_response_editing', models.BooleanField(default=True)),
                ('allow_public_registration', models.BooleanField(default=True)),
                ('require_email', models.BooleanField(default=False)),
                ('require_phone', models.BooleanField(default=False)),
                ('is_search_engine_visible', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-starts_at', 'internal_name'],
            },
        ),
        migrations.CreateModel(
            name='EventTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banner_image', models.ImageField(blank=True, upload_to='events/banners/')),
                ('background_image', models.ImageField(blank=True, upload_to='events/backgrounds/')),
                ('logo_image', models.ImageField(blank=True, upload_to='events/logos/')),
                ('primary_color', models.CharField(default='#31572c', max_length=7)),
                ('secondary_color', models.CharField(default='#b08968', max_length=7)),
                ('background_color', models.CharField(default='#f8f7f3', max_length=7)),
                ('text_color', models.CharField(default='#1f2933', max_length=7)),
                ('button_color', models.CharField(default='#31572c', max_length=7)),
                ('button_text_color', models.CharField(default='#ffffff', max_length=7)),
                ('border_radius', models.PositiveSmallIntegerField(default=8)),
                ('theme_mode', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=16)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='events.event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=8)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('location_address', models.CharField(blank=True, max_length=255)),
                ('location_description', models.TextField(blank=True)),
                ('success_message', models.TextField(blank=True)),
                ('decline_message', models.TextField(blank=True)),
                ('registration_closed_message', models.TextField(blank=True)),
                ('additional_information', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='events.event')),
            ],
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'starts_at'], name='events_even_status_5c3d55_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['slug'], name='events_even_slug_30eb0f_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventtranslation',
            constraint=models.UniqueConstraint(fields=('event', 'language'), name='unique_event_translation_language'),
        ),
    ]
