# Generated by Django 5.2.17 on 2026-08-04 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-starts_at', 'internal_name'], 'verbose_name': 'ивент', 'verbose_name_plural': 'ивенты'},
        ),
        migrations.AlterModelOptions(
            name='eventtheme',
            options={'verbose_name': 'оформление ивента', 'verbose_name_plural': 'оформление ивента'},
        ),
        migrations.AlterModelOptions(
            name='eventtranslation',
            options={'verbose_name': 'перевод ивента', 'verbose_name_plural': 'переводы ивента'},
        ),
    ]
