# Generated by Django 5.2.17 on 2026-08-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options_alter_eventtheme_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('registration_closed', 'Регистрация закрыта'), ('completed', 'Завершён'), ('archived', 'В архиве')], default='draft', max_length=32),
        ),
        migrations.AlterField(
            model_name='eventtheme',
            name='theme_mode',
            field=models.CharField(choices=[('light', 'Светлая'), ('dark', 'Тёмная')], default='light', max_length=16),
        ),
    ]
