# Generated by Django 5.2.17 on 2026-08-04 20:44

from django.db import migrations, models


def copy_banner_to_translations(apps, schema_editor):
    EventTheme = apps.get_model("events", "EventTheme")
    EventTranslation = apps.get_model("events", "EventTranslation")
    for theme in EventTheme.objects.exclude(banner_image=""):
        EventTranslation.objects.filter(event_id=theme.event_id).update(banner_image=theme.banner_image)


def restore_default_banner(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    EventTheme = apps.get_model("events", "EventTheme")
    EventTranslation = apps.get_model("events", "EventTranslation")
    for theme in EventTheme.objects.all():
        event = Event.objects.get(pk=theme.event_id)
        translation = EventTranslation.objects.filter(event_id=event.pk, language=event.default_language).first()
        if translation and translation.banner_image:
            theme.banner_image = translation.banner_image
            theme.save(update_fields=["banner_image"])


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_status_alter_eventtheme_theme_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtranslation',
            name='banner_image',
            field=models.ImageField(blank=True, upload_to='events/banners/'),
        ),
        migrations.RunPython(copy_banner_to_translations, restore_default_banner),
        migrations.RemoveField(
            model_name='eventtheme',
            name='banner_image',
        ),
    ]
