# Generated by Django 5.2.17 on 2026-08-05 07:46

import django.core.validators
from django.db import migrations, models

import apps.events.validators


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_eventtheme_banner_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='allow_response_editing',
        ),
        migrations.AlterField(
            model_name='eventtheme',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='events/backgrounds/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'webp'), message='Supported image formats: JPEG, PNG, and WebP.'), apps.events.validators.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='eventtheme',
            name='logo_image',
            field=models.ImageField(blank=True, upload_to='events/logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'webp'), message='Supported image formats: JPEG, PNG, and WebP.'), apps.events.validators.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='eventtranslation',
            name='banner_image',
            field=models.ImageField(blank=True, upload_to='events/banners/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'webp'), message='Supported image formats: JPEG, PNG, and WebP.'), apps.events.validators.validate_image_upload]),
        ),
    ]
