# Generated by Django 5.2.17 on 2026-08-04 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminprofile',
            options={'verbose_name': 'роль администратора', 'verbose_name_plural': 'роли администраторов'},
        ),
    ]
