# Generated by Django 5.2.17 on 2026-08-05 06:13

from django.conf import settings
from django.db import migrations


def normalize_admin_users(apps, schema_editor):
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(app_label, model_name)
    for user in User.objects.all():
        email = (user.email or "").strip().lower()
        if email and not User.objects.filter(username=email).exclude(pk=user.pk).exists():
            user.username = email
            user.email = email
        user.is_staff = True
        user.save(update_fields=["username", "email", "is_staff"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_adminprofile_options'),
    ]

    operations = [
        migrations.RunPython(normalize_admin_users, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='AdminProfile',
        ),
    ]
