# Generated by Django 5.2.17 on 2026-08-04 19:18

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('attendance_status', models.CharField(choices=[('attending', 'Attending'), ('declined', 'Declined')], max_length=16)),
                ('guest_count', models.PositiveIntegerField(default=1)),
                ('comment', models.TextField(blank=True)),
                ('edit_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'attendance_status'], name='registratio_event_i_9c8ca6_idx'), models.Index(fields=['edit_token'], name='registratio_edit_to_cafb3c_idx')],
            },
        ),
    ]
