# Generated by Django 5.2.17 on 2026-08-05 06:49

from django.db import migrations, models


def total_guests_to_additional_guests(apps, schema_editor):
    Registration = apps.get_model("registrations", "Registration")
    Registration.objects.filter(attendance_status="attending", guest_count__gt=0).update(
        guest_count=models.F("guest_count") - 1
    )


def additional_guests_to_total_guests(apps, schema_editor):
    Registration = apps.get_model("registrations", "Registration")
    Registration.objects.filter(attendance_status="attending").update(
        guest_count=models.F("guest_count") + 1
    )


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_alter_registration_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='guest_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(total_guests_to_additional_guests, additional_guests_to_total_guests),
    ]
