# Generated by Django 5.2.17 on 2026-08-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_event_allow_response_editing_and_more'),
        ('registrations', '0003_alter_registration_guest_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='registration',
            name='ip_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['event', 'created_at'], name='registratio_event_i_f44d95_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['event', 'email'], name='registratio_event_i_d890ad_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['event', 'phone'], name='registratio_event_i_60a549_idx'),
        ),
    ]
