# Generated by Django 5.2.17 on 2026-08-04 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'запись журнала', 'verbose_name_plural': 'журнал действий'},
        ),
    ]
