# Generated by Django 5.2.17 on 2026-08-04 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visitor_key', models.CharField(max_length=64)),
                ('path', models.CharField(max_length=512)),
                ('language', models.CharField(blank=True, max_length=8)),
                ('user_agent', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='events.event')),
            ],
            options={
                'indexes': [models.Index(fields=['event', 'visitor_key'], name='analytics_e_event_i_328bc8_idx'), models.Index(fields=['event', 'created_at'], name='analytics_e_event_i_1237ad_idx')],
            },
        ),
    ]
