# Generated by Django 5.2.17 on 2026-08-04 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventpageview',
            options={'verbose_name': 'просмотр страницы', 'verbose_name_plural': 'просмотры страниц'},
        ),
    ]
